import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Company from "../components/company";

export default function Home() {
  const companyData = [
    {
      headquarters: {
        address: "Rocket Road",
        city: "Hawthorne",
        state: "California",
      },
      links: {
        website: "https://www.spacex.com/",
        flickr: "https://www.flickr.com/photos/spacex/",
        twitter: "https://twitter.com/SpaceX",
        elon_twitter: "https://twitter.com/elonmusk",
      },
      name: "SpaceX",
      founder: "Elon Musk",
      founded: 2002,
      employees: 8000,
      vehicles: 3,
      launch_sites: 3,
      test_sites: 1,
      ceo: "Elon Musk",
      cto: "Elon Musk",
      coo: "Gwynne Shotwell",
      cto_propulsion: "Tom Mueller",
      valuation: 52000000000,
      summary:
        "SpaceX designs, manufactures and launches advanced rockets and spacecraft. The company was founded in 2002 to revolutionize space technology, with the ultimate goal of enabling people to live on other planets.",
      id: "5eb75edc42fea42237d7f3ed",
    },
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title className={styles.title}>SpaceX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spacecraft.svg" />
      </Head>

      <main className={styles.main}>
        <section className={styles.banner}>
          <h1 className={styles.title}>SpaceX</h1>
          <p>All you need to know and more!</p>
        </section>
        <Company data={companyData[0]}></Company>
        <section className={styles.navToData}>
          <Link href="/category/launches">
            <a>Let's get started!</a>
          </Link>
        </section>
      </main>

      <footer className={styles.footer}>
        <p>
          <strong>Disclaimer</strong>: We are <strong>not</strong> affiliated,
          associated, authorized, endorsed by, or in any way officially
          connected with Space Exploration Technologies Corp (SpaceX), or any of
          its subsidiaries or its affiliates.
        </p>
        <h4 className={styles.navToExtSource}>
          <a href="https://github.com/r-spacex/SpaceX-API">
            Credits to SpaceX API
          </a>
        </h4>
      </footer>
    </div>
  );
}
