import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Company from "../components/company";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title className={styles.title}>SpaceX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spacecraft.svg" />
      </Head>

      <main className={styles.main}>
        <section className={styles.banner}>
          <h1 className={styles.title}>SpaceX</h1>
          <p>All you need to know and more!</p>
        </section>
        <Company></Company>
        <section className={styles.navToData}>
          <Link href="/category/launches">
            <a>Let's get started!</a>
          </Link>
        </section>
      </main>

      <footer className={styles.footer}>
        <p>
          <strong>Disclaimer</strong>: We are <strong>not</strong> affiliated,
          associated, authorized, endorsed by, or in any way officially
          connected with Space Exploration Technologies Corp (SpaceX), or any of
          its subsidiaries or its affiliates.
        </p>
        <h4 className={styles.navToExtSource}>
          <a href="https://github.com/r-spacex/SpaceX-API">
            Credits to SpaceX API
          </a>
        </h4>
      </footer>
    </div>
  );
}
